# Generated by Django 4.0.3 on 2022-03-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(default='', max_length=100)),
                ('port', models.IntegerField(blank=True, default=None, null=True)),
                ('email_id', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.CharField(max_length=100)),
                ('meeting_url', models.CharField(max_length=200)),
                ('org', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('protocol', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('agent', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('referer', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('validIp', models.BooleanField(default=False)),
                ('locStatus', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('countryCode', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('regionName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, default=None, max_length=100, null=True)),
                ('lon', models.FloatField(blank=True, default=None, max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('isp', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ip_org', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('orgAs', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
