# Generated by Django 4.0.3 on 2022-03-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertrace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='unidentified',
            field=models.BooleanField(default=False),
        ),
    ]
